name: indigenadigital
favicon: null
layout_spectrum: 0.02358
typography_spectrum: 1
title: 'indigena digital '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#29295b'
    - '#dacfcb'
    - '#e2487e'
    - '#5c5c9c'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
