name: indigenadigital
favicon: null
layout_spectrum: 0.02358
typography_spectrum: 1
title: 'indigena digital '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#dfe2e7'
    - '#736d4f'
    - '#d59a7c'
    - '#900010'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
